### ISSUE TITLE
1.20.1 datapack query

### ISSUE THREAD

**Issue by polykatt** [LarsMans64/SeparatedLeaves#16]
The guide that you've provided states that for versions after 1.19.2 require a biome.json file so I just want to make sure that I have it right. So in the example it goes data/atmospheric/separated_leaves and then inside that folder would be where the biomes.json file goes alongside the morado.json, right? And you only need one biome.json file for each mod or for every tree json file that's added?

I'm new to this, just want to be sure ^-^

**Comment by LarsMans64** [comment]
Only one per mod/namespace :)

**Comment by polykatt** [comment]
Okay, thanks so much!
