### ISSUE TITLE
"minecraft:stripper_warped_stems" ???

### ISSUE THREAD

**Issue by unilock** [LarsMans64/SeparatedLeaves#17]
https://github.com/TeamDiopside/SeparatedLeaves/blob/8af5044b3e3807f9af569a4c0d50dff8debe7f5f/common/src/main/resources/data/terralith/separated_leaves/enchanted_oak.json#L3

What was this supposed to be? :p

**Comment by LarsMans64** [comment]
the unknown sexy variant
