### ISSUE TITLE
[1.20.1 Forge] Separated Leaves causes issues with structure mods/datapacks that rely on leaves surviving with any logs

### ISSUE THREAD

**Issue by TelepathicGrunt** [LarsMans64/SeparatedLeaves#4]
In my mod Bumblezone, I have some structures that mix and match certain logs and leaves to create a variety of interesting trees. Many other mods and datapacks do the same. 

However when Separated Leaves is on, it makes no distinction between structure spawned leaves and non-structure leaves. And so it decays the leaves in our structures and makes it look awful. I choose not to make the leave persistent property set to true as I want it to decay if attached to no logs at all but otherwise, should remain.

This is what I am seeing currently in TNP Limitless 7 with my mod and Separated Leaves on. This is my White Sempiternal Sanctum structure spawning trees using NBT structure files.
![image](https://github.com/TeamDiopside/SeparatedLeaves/assets/40846040/774ef945-9e23-4389-b4ca-d7e24b53b28d)

This is the intended look:
![image](https://github.com/TeamDiopside/SeparatedLeaves/assets/40846040/1f00263d-63cd-4ee0-abeb-090e570f2dd3)

I also have a Hanging Gardens structure that does the same thing of mix and matching leaves and logs for fun.
![image](https://github.com/TeamDiopside/SeparatedLeaves/assets/40846040/47949f47-94e0-4686-90ef-9448f6c9a070)
![image](https://github.com/TeamDiopside/SeparatedLeaves/assets/40846040/447d44df-4aab-4dc1-9edd-1f2a6ceb08eb)

**Comment by LarsMans64** [comment]
I'm sorry, but the reason that it makes no distinction between structure spawned leaves and non-structure leaves, is because there is no difference between the two. There is no way for me to tell if the leaves came from a structure and to which logs they should connect. I guess the only solutions are to make sure the leaves in the structure are persistent, or to make a datapack to change which blocks the leaves stick to, or to play without separated leaves.

**Comment by TelepathicGrunt** [comment]
Alternative, add a structure blacklist config and stick my mod's structures by default in it and pack makers can add more. You can check if location is in bounds of a structure and not perform your logic if it is in a blacklisted structure

Example:
https://github.com/TelepathicGrunt/RepurposedStructures/blob/2058409defd3a72924aa322fee0938377156e626/src/main/java/com/telepathicgrunt/repurposedstructures/mixin/features/NoDeltasInStructuresMixin.java#L32-L35

**Comment by TelepathicGrunt** [comment]
Actually this code example is better. It can just be a tag and two line to check if in bounds of any structure in the tag
https://github.com/TelepathicGrunt/Bumblezone/blob/f4678292c7f965ec6943ae50d15933f4c80abda8/common/src/main/java/com/telepathicgrunt/the_bumblezone/worldgen/structures/SempiternalSanctumBehavior.java#L34-L35

**Comment by LarsMans64** [comment]
Oh I didn't know that, thank you!

**Comment by ffuentesm** [comment]
I am still having this problem with Yungs Better mineshaft 
The Structure uses Oak logs and spruce leaves, as well as other combinations of logs and leaves in their mines. 
As you can see in the minimap, the entire place is decaying 
![image](https://github.com/TeamDiopside/SeparatedLeaves/assets/44974827/fb414013-dfed-4b58-9b4e-9c35631af552)
![image](https://github.com/TeamDiopside/SeparatedLeaves/assets/44974827/e30f04f8-1d32-4a62-a064-876d58e136dd)
